- id: jsonschema-validator
  name: JSON Schema Validator
  description: Validate JSON/JSON5 documents against JSON Schema (supports all drafts, JSON5, reference overrides)
  entry: jsonschema-validator
  language: golang
  pass_filenames: true
  stages: [manual]
  files: ''
  additional_dependencies: []
  minimum_pre_commit_version: '2.9.0'
  require_serial: false
